from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v119_worker1_existing_C6_codegen_lifetime_diagnostic_sc-16g-2';r=b/'rep'/v;m=json.loads((r/'diagnostic_source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());runtime=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert d['complete'] and d['failure'] is None and len(d['all_jobs'])==2 and all(x['actual_exit']==0 and x['stop_reason'] is None for x in d['all_jobs']);assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13
assert all(value=='0' for value in runtime['actual_waits'].values()) and runtime['all_self_jobs_terminal'] and not runtime['owned_current_live'];assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for label,x in list(m['sources'].items())+list(m['tools'].items())+list(m['existing_inputs'].items())+list(m['closed118_dependencies'].items())+[('shared_doc',m['shared_identity_document'])]:assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],label
for f,s in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s
assert Path(m['existing_inputs']['old_resource_gate_exit']['path']).read_text().strip()=='1';assert sha(root/'race_tests/nsa/submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'existing_CPP_first_IR_diagnostic_completed_no_optimization_claim','source_reference':m['sources']['candidate118'],'original_runtime_result':d,'runtime_final':runtime,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'manual_IR_observations':json.loads((r/'manual_IR_phase_observation.json').read_text()),'old118_MT90_gate1_retained':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
files=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];inventory={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(inventory,indent=2)+chr(10));assert all(sha(root/f)==s for f,s in inventory.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip()
paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f','--']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V119_CLOSURE_STAGED',len(staged),len(inventory),'0outside')
