from pathlib import Path
import ast,hashlib,json,difflib,subprocess
root=Path('/root/tilelang-metax/race_tests/nsa');v='v081_codex_power_s24_lazy_dispatch_sc-16g-2';r=root/'rep'/v;base=subprocess.check_output(['git','show','39ff49e7b:race_tests/nsa/submission.py'],text=True);assert hashlib.sha256(base.encode()).hexdigest()=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
paths=[root/'experiments/v076_codex_power_s1_v_hybrid_pack_sc-16g-2/s1_kernel.py',root/'experiments'/v/'s248_kernel.py',root/'experiments/v079_codex_power_s1_case4_dense_sc-16g-2/s1_case4_kernel.py'];helpers=[]
for path in paths:
 text=path.read_text();fn=next(x for x in ast.parse(text).body if isinstance(x,ast.FunctionDef));start=min(x.lineno for x in fn.decorator_list)-1;helpers.append(''.join(text.splitlines(True)[start:fn.end_lineno]))
cases=json.loads((root/'official_case.json').read_text());ids=[2,4,5,6,7,8,9,10,11,12,13,14];entries=[]
for ci in ids:
 c=cases[ci-1];key=tuple(c[x] for x in ['B','SEQ_LEN','H','HQ','D','S','block_size'])+(bool(c['is_causal']),);factory='_make_power_s1_v_hybrid_pack' if ci==6 else '_make_power_s8_output_pair' if ci in [10,11,12] else '_make_power_s1_case4_dense';entries.append('    ('+repr(key)+', '+factory+'),')
registry="\ndef _power_install_lazy_code(key, factory):\n    def first_call(*tensor_args):\n        kernel = factory(*key)\n        _KERNEL_CACHE[key] = kernel\n        return kernel(*tensor_args)\n    _KERNEL_CACHE[key] = first_call\n\nfor _power_key, _power_factory in (\n"+'\n'.join(entries)+"\n):\n    _power_install_lazy_code(_power_key, _power_factory)\n"
(root/'experiments'/v/'lazy_dispatch.py').write_text(registry)
source='# codex-power v081\n'+base+'\n'+'\n'.join(helpers)+registry;a=ast.parse(base);b=ast.parse(source);assert ast.dump(ast.Module(body=b.body[:len(a.body)],type_ignores=[]))==ast.dump(a);p=Path('/tmp/nsa_power_v081_s24_lazy.py');p.write_text(source)
parent=(root/'submission/v080_codex_power_s1_d64_dispatch_sc-16g-2/submission.py').read_text();assert hashlib.sha256(parent.encode()).hexdigest()=='31a6d042336de68ab75c4be3e1777089324490d639ac3021c90381c268a714a1';(root/'experiments'/v/'source_diff.patch').write_text(''.join(difflib.unified_diff(parent.splitlines(True),source.splitlines(True),fromfile='exact_power_v080',tofile=str(p))))
(r/'source_identity.json').write_text(json.dumps({'candidate_path':str(p),'candidate_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'baseline_sha256':hashlib.sha256(base.encode()).hexdigest(),'parent_sha256':hashlib.sha256(parent.encode()).hexdigest(),'originalprefix_and_entryAST_exact':True,'helper_dependencies':{str(f):hashlib.sha256(f.read_bytes()).hexdigest() for f in paths},'s248_compute_body_exact77_excluding_shape_asserts':True,'new_dispatch_cases':[10,11],'lazy_dispatch_cases':ids,'lazycache':'key+factory compiledcode only, closure not input retention, actualJITKernel replacesentry during first normal call'},indent=2)+'\n');print('selfcontainedcandidate',p,hashlib.sha256(p.read_bytes()).hexdigest())
