from pathlib import Path
from decimal import Decimal
import json,statistics
p=Path('/root/tilelang-metax/race_tests/nsa');v='v081_codex_power_s24_lazy_dispatch_sc-16g-2';r=p/'rep'/v;formal=json.loads((r/'formal_all14_summary.json').read_text());risk=json.loads((r/'risk_summary.json').read_text());prof=json.loads((r/'mcprof_summary.json').read_text());resources=json.loads((r/'resource_summary.json').read_text());f=r/'report_sc-16g-2.md';body=f.read_text().split('## 5.')[0]
body+='## 5. Benchmark\n\nNative full naive_nsa, F16 causal seed0, warmup10/repeat50, unchanged tolerance. B-I-C-C-I-B twice, 4 samples per source. Unit us; all raw values retained.\n\n| case | v28 | parent80 | v081 | vs v28 | vs 80 |\n|---|---:|---:|---:|---:|---:|\n'
for x in formal['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v080']),Decimal(m['power_v081']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
body+='\nFixed risk confirmation for EVERY positive formal delta versus either source, once only. Initial positive data are preserved; no byte-identity timing waiver.\n\n| case | v28 | parent80 | v081 | vs v28 | vs 80 |\n|---|---:|---:|---:|---:|---:|\n'
for x in risk['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v080']),Decimal(m['power_v081']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
n=len(risk['cases']);body+='\nExact candidate checks: {} across14 cases; whole experiment including controls: {}. Target8/24, formal56/168, risk{}/{}, exactarchive14/14. Count merged CSVs once; percase copies and metadata/profile/import observations are not additional reference checks.\n'.format(78+4*n,206+12*n,4*n,12*n)
body+='\n## 6. Profile and resource evidence\n\nCase11 representative mcProfiler counts2 per source, original separate warm10+20 driver; requires_grad=False here versus native=True. Not official latency or runtime-equivalence proof. Expected1024waves/2097152 output bytes; scope consistency necessary but not exclusive.\n\n| metric mean | parent80 | v081 |\n|---|---:|---:|\n'
for k in ['waves','read_bytes','write_bytes','l2_hit_pct','shared_nonconflict_pct','conflict_cycles','load_latency_cycles','mte_pct','mma_pct']:
 vals=[]
 for label in ['parent_v080','power_v081']:
  a=[x[k] for x in prof if x['variant']==label and x[k] is not None];vals.append('{:.4f}'.format(statistics.mean(a)) if len(a)==2 else 'unavailable')
 body+='| '+k+' | '+vals[0]+' | '+vals[1]+' |\n'
body+='\n| case/source | MT | ST | stackB | dynamic sharedB | static max warps/PEU |\n|---|---:|---:|---:|---:|---:|\n'
for x in resources:body+='| {}/{} | {} | {} | {} | {} | {} |\n'.format(x['case'],x['variant'],x['MT'],x['ST'],x['stack_bytes'],x['dynamic_shared_bytes_host'],x['static_max_warps_per_PEU'])
body+='\nCLI static shared0 does not mean total shared0. Dynamic shared is read from actual host source; minblocks warning retained; static maxwarps is not measured occupancy.\n\nCold imports (one process observation each, no attention/reference):\n\n| source | source exec seconds | process peak KiB | compiled/lazy entries |\n|---|---:|---:|---:|\n'
for label in ['parent_v080','power_v081']:
 x=json.loads((r/('cold_import_'+label+'.json')).read_text());body+='| {} | {:.6f} | {} | {}/{} |\n'.format(label,x['source_exec_seconds'],x['process_peak_rss_after_source_kib'],x['compiled_JITKernel_entries'],x['lazy_code_entries'])
body+='\nThis import sample is not OOM stability proof or scored kernel timing. mcTracer prior timeout124/header-only, no new timeline. No working ISA decoder or calibrated actual sGPU roofs, so no invented ISA or Roofline. mx-smi summaries are read-only runtime state, not per-kernel throughput/occupancy.\n\n## 7. Conclusion\n\nS2/S4 target screen and fullnative show improvement; full14 correctness passes. All initial and confirmation positive deltas retained. External full14 OJ scores pending; strict no-regression has not been proved. Status inconclusive, archive only, main originalv28 and prior candidates unchanged. Further work must address remaining case risks and verify real OJ; never treat byte-identical code or import-memory wins as a performance waiver.\n'

for before,after in {'## 5. Benchmark': '## 5. Benchmark 对比', '## 6. Profile and resource evidence': '## 6. Profile 指标变化', '## 7. Conclusion': '## 7. 实验总结', 'Native full naive_nsa, F16 causal seed0, warmup10/repeat50, unchanged tolerance. B-I-C-C-I-B twice, 4 samples per source. Unit us; all raw values retained.': '原始完整naive_nsa、F16 causal、seed0、warmup10/repeat50、容差不变；B-I-C-C-I-B两轮，各源码4样本。单位us，全部原始数据保留。', 'Fixed risk confirmation for EVERY positive formal delta versus either source, once only. Initial positive data are preserved; no byte-identity timing waiver.': '首轮相对任一对照出现正差的全部case统一固定复测一次。首轮正差保留，不以代码相同豁免时延退化。', 'Exact candidate checks:': '精确候选参考检查：', 'across14 cases; whole experiment including controls:': '覆盖14项；含对照全组检查：', 'Count merged CSVs once; percase copies and metadata/profile/import observations are not additional reference checks.': '合并CSV仅计一次，逐case副本、metadata/profile/import不重复计参考。', 'S2/S4 target screen and fullnative show improvement; full14 correctness passes. All initial and confirmation positive deltas retained. External full14 OJ scores pending; strict no-regression has not been proved. Status inconclusive, archive only, main originalv28 and prior candidates unchanged. Further work must address remaining case risks and verify real OJ; never treat byte-identical code or import-memory wins as a performance waiver.': 'S2/S4目标screen及正式完整native改善，全14正确性通过；首轮及复测所有正差保留。外部完整14项OJ分数仍待验证，严格无退化未证明。本版inconclusive，仅归档，主入口原始v28和此前候选不变。后续须处理剩余case风险并核对真实OJ，不能把代码一致或导入内存下降当成速度豁免。'}.items():body=body.replace(before,after)

for before,after in {'Case11 representative mcProfiler counts2 per source, original separate warm10+20 driver; requires_grad=False here versus native=True. Not official latency or runtime-equivalence proof. Expected1024waves/2097152 output bytes; scope consistency necessary but not exclusive.': 'case11代表性mcProfiler各2样本，独立原始warm10+20 driver；本段requires_grad=False，native=True。不算官方时延，也不证明运行时等价。应为1024waves/2097152输出字节；scope一致仅为必要条件。', 'CLI static shared0 does not mean total shared0. Dynamic shared is read from actual host source; minblocks warning retained; static maxwarps is not measured occupancy.': 'CLI静态shared0不等于总shared0；动态shared取实际host字段，保留minblocks警告，static maxwarps不是实测占用。', 'Cold imports (one process observation each, no attention/reference):': '冷import每源码独立进程观测一次，无attention/参考调用：', 'This import sample is not OOM stability proof or scored kernel timing. mcTracer prior timeout124/header-only, no new timeline. No working ISA decoder or calibrated actual sGPU roofs, so no invented ISA or Roofline. mx-smi summaries are read-only runtime state, not per-kernel throughput/occupancy.': '单次import样本不是OOM稳定性证明或计分kernel时延。mcTracer前期timeout124/仅header，本版未新重试。没有可用ISA解码器或已标定sGPU实际roof，不伪造汇编/Roofline。mx-smi仅只读运行状态，不是逐kernel吞吐/占用。'}.items():body=body.replace(before,after)
body=body.replace('## 7. 实验总结','冷导入编译entries2→0，执行时间0.633→0.340s；双方在执行候选source前历史峰值已约22GiB，after-source峰值差只有约33MiB。未证明低内存组件归因或OOM风险解除，不把这个未计分的导入差当作kernel收益。\n\n## 7. 实验总结')
body=body.replace('冷导入编译entries2→0','C11指标：shared效率59.945%→100%、conflict2.34→0，load49.585→48.235仅略降，MTE43.285→46.145、MMA5.635→6.995，L2命中80.91→78.14反而下降、全局流量接近。动态shared4608→2048B，但MT68→80、static maxwarps7→6，不宣称占用提高；这些证据与16.087%正式时延改善方向一致，不足以全归因bank冲突。C10同样MT60→82/maxwarps8→5而时间改善，资源单指标不决定最终时延。\n\n冷导入编译entries2→0')
f.write_text(body);assert body.count('## ')==7;print('final report generated',78+4*n,206+12*n)
