from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v114_worker1_reallocated_baseline_original_C11_screen_sc-16g-2';r=b/'rep'/v;n=r/'native_screen';d=json.loads((n/'diagnostic_result.json').read_text());s=json.loads((n/'screen_summary.json').read_text());assert d['runtime_protocol_completed'] and d['clean_candidate_fullrefs']==d['observed_candidate_fullrefs']==4 and d['clean_inclusive_fullrefs']==d['observed_inclusive_fullrefs']==12;assert len(d['all_jobs'])==12 and all(j['native_exit']==0 and j['clean_process_accepted'] for j in d['all_jobs']);assert all((n/k).read_text().strip()=='0' for k in ['launcher_actual.exit','native_supervisor_actual.exit','controller_actual.exit','diagnostic.exit','screen_analysis_actual.exit']);assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13;assert s['allcandidate_lt_allparent'] and not s['ranges_overlap'];assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
m=json.loads((n/'native_source_manifest.json').read_text())
for x in list(m['sources'].values())+list(m['tools'].values())+[m[k] for k in ['frozen_compiled_gate','shared_identity_document','existing_parent_C11_device','frozen_compiled_gate_actual_exit','preserved_compiled_gate_original_exit']]:assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
for name,sha in json.loads((r/'shared_inputs_identity.json').read_text())['files'].items():assert hashlib.sha256((root/name).read_bytes()).hexdigest()==sha
assert (b/'rep/v113_worker1_s4_global_softmax_sc-16g-2/native_screen/diagnostic.exit').read_text().strip()=='1'
for x in s['raw_samples']:assert hashlib.sha256(Path(x['raw_CSV']).read_bytes()).hexdigest()==x['CSV_SHA']
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'fixed_C11_native_complete_selected_local_gain_full14_pending','candidate_source113':m['sources']['power_v113'],'actual_native_result':d,'actual_summary':s,'runtime_final':json.loads((r/'runtime_final.json').read_text()),'counts':json.loads((r/'reference_count_scope.json').read_text()),'source_codegen_scope':json.loads((r/'case_impact_scope.json').read_text()),'old4GiB_refusal1_preserved':True,'new_budget_not_futureguarantee':True,'no_adaptive_measurements':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for a in ['experiments','hack','rep','submission']:(b/a/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for a in ['experiments','hack','rep','submission'] for f in (b/a/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==sha for f,sha in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((b/a/v).relative_to(root)) for a in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('V114_CLOSED',len(staged),len(idx),'4C12inclusiveclean')
