from pathlib import Path
import ast,copy,json,hashlib,difflib
root=Path('/root/tilelang-metax');v='v210_worker2_c8_serial_query_pair_subagent2';r=root/'race_tests/nsa/rep'/v;x=root/'race_tests/nsa/experiments'/v
parent=root/'race_tests/nsa/submission/v084_codex_power_s1_d32_d128_pair_sc-16g-2/submission.py';s=parent.read_text();assert hashlib.sha256(s.encode()).hexdigest()=='4c674c79e4128f3c9f233fa6694c1a8f825d1048293accd9250fb5e2d86472b0'
t=ast.parse(s);base=next(n for n in t.body if isinstance(n,ast.FunctionDef) and n.name=='_make_power_s1_case4_dense');n=copy.deepcopy(base);n.name='_make_worker2_c8_serial_query_pair'
f=next(z for z in n.body if isinstance(z,ast.FunctionDef) and z.name=='native_sparse_attention');w=f.body[0];oldctx=copy.deepcopy(w.items);oldbody=copy.deepcopy(w.body)
first=next(i for i,z in enumerate(w.body) if isinstance(z,ast.For) and isinstance(z.target,ast.Name) and z.target.id=='part');allocs=copy.deepcopy(w.body[:first]);core=copy.deepcopy(w.body[first:]);assert sum(isinstance(q,ast.Call) and isinstance(q.func,ast.Attribute) and q.func.attr=='sync_warp' for q in ast.walk(ast.Module(core,[])))==7
w.items=ast.parse('with T.Kernel((seq_len + 1) // 2, batch * kv_heads, threads=64) as (query_pair, batch_head):\n pass').body[0].items
loop=ast.parse('for query_step in T.serial(2):\n token = query_pair * 2 + query_step\n if token < seq_len:\n  pass\n if query_step == 0:\n  T.sync_warp()').body[0];loop.body[1].body=core;w.body=allocs+[loop]
undo=copy.deepcopy(n);undo.name=base.name;uw=next(z for z in undo.body if isinstance(z,ast.FunctionDef) and z.name=='native_sparse_attention').body[0];uw.items=oldctx;ul=uw.body[-1];uw.body=uw.body[:-1]+ul.body[1].body
assert ast.dump(undo,include_attributes=False)==ast.dump(base,include_attributes=False)
assert not any(isinstance(q,ast.Call) and isinstance(q.func,ast.Attribute) and q.func.attr.startswith('alloc_') for q in ast.walk(loop))
ast.fix_missing_locations(n);helper=ast.unparse(n)+'\n';key=(2,4096,1,16,64,1,16,True);candidate='# codex-power v210\n'+s.split('\n',1)[1]+'\n\n'+helper+'\n_power_install_lazy_code('+repr(key)+', '+n.name+')\n';p=Path('/tmp/nsa_worker2_v210_c8_serial_query_pair.py');p.write_text(candidate);ct=ast.parse(candidate)
assert len(ct.body)==len(t.body)+2 and ast.dump(ast.Module(ct.body[:len(t.body)],[]),include_attributes=False)==ast.dump(t,include_attributes=False);assert ast.literal_eval(ct.body[-1].value.args[0])==key
(x/'serial_query_pair_kernel.py').write_text(helper);(x/'source_diff.patch').write_text(''.join(difflib.unified_diff(s.splitlines(keepends=True),candidate.splitlines(keepends=True),fromfile=str(parent),tofile=str(p))))
identity={'candidate_path':str(p),'candidate_sha256':hashlib.sha256(candidate.encode()).hexdigest(),'parent_sha256':hashlib.sha256(s.encode()).hexdigest(),'factory_name':n.name,'dispatch_key':list(key),'official_case_number':8,'prefix_14_AST_nodes_equal':True,'inverse_grid_loop_token_guard_boundary_restore_whole_factory_AST_equal':True,'original_array_allocations_outside_serial_loop_equal':True,'perquery_core_AST_identical':True,'Num_float32_elements':16,'shared_half_elements':1024,'query_step_loop':'T.serial(2)','token':'query_pair*2+query_step','whole_wave_tail_guard':'token<seq_len','original_sync_sites_perquery':7,'extra_boundary_sync_site':'after entire q0Output/gather, before q1firstQsharedwrite; query_step==0','planned_executed_syncs_perpair':15,'source_sync_sites':8,'query_content_cache':False,'independent_Indices_KV_perquery':True,'perquery_Qreload_Num_den_max_reset_AST_unchanged':True,'valid_branch_Score_P_V_overwrite_before_read_AST_unchanged':True,'original_math_dtypes_vector_paths_unchanged':True,'exact_import_count':len([z for z in ct.body if isinstance(z,(ast.Import,ast.ImportFrom))]),'source_only_import_compile_attention_native':[0,0,0,0],'actualCPP_IR_executioncounts_resources':'UNAVAILABLE_not_compiled'}
assert identity['exact_import_count']==3;(r/'source_identity.json').write_text(json.dumps(identity,indent=2)+'\n');print(json.dumps(identity,indent=2))
