from pathlib import Path
from decimal import Decimal
import json,statistics
p=Path('/root/tilelang-metax/race_tests/nsa');v='v083_codex_power_s1_d32_register_sc-16g-2';r=p/'rep'/v;formal=json.loads((r/'formal_all14_summary.json').read_text());risk=json.loads((r/'risk_summary.json').read_text());prof=json.loads((r/'mcprof_summary.json').read_text());resources=json.loads((r/'resource_summary.json').read_text());f=r/'report_sc-16g-2.md';body=f.read_text().split('## 5.')[0]
body+='## 5. Benchmark\n\nOriginal full naive_nsa, F16 causal seed0, W10R50 and tolerance unchanged. B-I-C-C-I-B twice,4 samples/source. Unit us. Every initial and fixed-confirmation sample retained, no byte-identity waiver.\n\n| case | v28 | parent81 | v082 | vs v28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in formal['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v083']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
body+='\nFixed confirmation of EVERY positive formal delta versus original or parent,once only.\n\n| case | v28 | parent81 | v082 | vs v28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in risk['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v083']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
n=len(risk['cases']);body+='\nExact candidate checks {} across14cases; whole experiment {} includingcontrols. Target4/12,formal56/168,risk{}/{},exactarchive14/14. Count merged files only,percase copies/metadata/profile calls not extra references.\n'.format(74+4*n,194+12*n,4*n,12*n)
body+='\n## 6. Profile\n\nFresh parent preprobe and postnative current paired mcProfiler case1 counts2/source.64waves/64KiB plus bounded residual scope consistency necessary,not exclusive. DriverW10+20 requires_grad=False,native=True; no runtime-equivalence claim.\n\n| metric mean | parent81 | v082 |\n|---|---:|---:|\n'
for k in ['waves','read_bytes','write_bytes','l2_hit_pct','shared_nonconflict_pct','conflict_cycles','load_latency_cycles','mte_pct','mma_pct']:
 vals=[]
 for label in ['parent_v081','power_v083']:
  xs=[x[k] for x in prof if x['variant']==label and x[k] is not None];vals.append('{:.4f}'.format(statistics.mean(xs)) if len(xs)==2 else 'unavailable')
 body+='| '+k+' | '+vals[0]+' | '+vals[1]+' |\n'
body+='\n| source | MT | ST | stackB | dynamic sharedB | static maxwarps/PEU |\n|---|---:|---:|---:|---:|---:|\n'
for x in resources:body+='| {} | {} | {} | {} | {} | {} |\n'.format(x['variant'],x['MT'],x['ST'],x['stack_bytes'],x['dynamic_shared_bytes_host'],x['static_max_warps_per_PEU'])
body+='\nStatic shared0 doesnot mean total0,actual host dynamic shared is captured. Static maxwarps/raw achieved waves are not measured occupancy; minblocks warning kept. No working ISA decoder or calibrated actual sGPU roofs; mcTracer prior124/header-only not retried. mx-smi read-only summaries not perkernel bandwidth/occupancy.\n\n## 7. Conclusion\n\nSingle C1 dispatch added; other13 bodies/keys exactparent81. Full14 native correctness passes. Preserve every positive formal/risk difference; external OJ scores pending,no no-regression proof. Inconclusive archive only,main exactv28,prior candidates unchanged. Actual resource/profile and native latency must be interpreted together; no bank-only causal attribution.\n'

for before,after in {'## 5. Benchmark': '## 5. Benchmark 对比', '## 6. Profile': '## 6. Profile 指标变化', '## 7. Conclusion': '## 7. 实验总结', 'Original full naive_nsa, F16 causal seed0, W10R50 and tolerance unchanged. B-I-C-C-I-B twice,4 samples/source. Unit us. Every initial and fixed-confirmation sample retained, no byte-identity waiver.': '原始完整naive_nsa、F16 causal seed0、W10R50/容差不变。B-I-C-C-I-B两轮各4样本，单位us。所有原始/固定复测数据保留，不以代码一致豁免退化。', 'Fixed confirmation of EVERY positive formal delta versus original or parent,once only.': '首轮相对任一对照正差的所有case固定复测一次。', 'Exact candidate checks': '精确候选参考次数', 'across14cases; whole experiment': '覆盖14项；全组', 'Count merged files only,percase copies/metadata/profile calls not extra references.': '合并仅计一次，逐case副本/metadata/profile不是额外完整参考。', 'Fresh parent preprobe and postnative current paired mcProfiler case1 counts2/source.64waves/64KiB plus bounded residual scope consistency necessary,not exclusive. DriverW10+20 requires_grad=False,native=True; no runtime-equivalence claim.': 'fresh parent preprobe与native之后当前双版本mcProfiler各2样本。64waves/64KiB+小额未归因残量仅scope必要一致性；driverW10+20 gradFalse、nativeTrue，不宣称运行时等价。', 'Static shared0 doesnot mean total0,actual host dynamic shared is captured. Static maxwarps/raw achieved waves are not measured occupancy; minblocks warning kept. No working ISA decoder or calibrated actual sGPU roofs; mcTracer prior124/header-only not retried. mx-smi read-only summaries not perkernel bandwidth/occupancy.': '静态shared与实际host动态shared分别记录；static maxwarps/raw achieved不是实测占用，保留minblocks警告。无ISA解码器/已标定sGPU roof，mcTracer前期124/仅header未新重试，mx-smi只读状态不是逐kernel带宽。', 'Single C1 dispatch added; other13 bodies/keys exactparent81. Full14 native correctness passes. Preserve every positive formal/risk difference; external OJ scores pending,no no-regression proof. Inconclusive archive only,main exactv28,prior candidates unchanged. Actual resource/profile and native latency must be interpreted together; no bank-only causal attribution.': '仅C1新分支，其他13个body/keys精确parent81。完整14 native正确性检查与正式/固定风险数据全部留存，外部OJ待核对，无退化未证明。本版只归档候选，主入口原v28与此前版本不变；source/资源/profile/端到端一起判断，不仅凭去shared宣称收益。'}.items():body=body.replace(before,after)
body=body.replace('## 7. 实验总结','当前C1正式仅比v28快0.4276%、比parent81快2.321%，screen样本重叠，不能当稳健收益。C3固定比v28 +0.0628799%、C7比parent81 +0.13456%，所有原始/确认数据保留；按严格不退化门槛不提升，不能以字段未改或噪声猜测豁免。原formal137与case5恢复单独记录，metadata两次解析失配只改分析，不重跑native，候选SHA不变。\n\n## 7. 实验总结')
body=body.replace('## 7. 实验总结','raw metric组和description核准：load_latency_cycles属于Workgroup Memory的WG-load从issue到memopsdone，conflict也是WG指令，不能叫global/DRAM load延迟。新kernel无shared，工具填100%eff/0WG-load/0conflict只是零访问的报告行为，不当有效效率100或global零时延。zero_shared_raw_metric_context留原始group/description，表格仅保留raw字段。\n\n## 7. 实验总结')
body=body.replace('## 7. 实验总结','当前双版本：global read76704→75808B、write65856不变、L2 76.225→85.63%，MTE5.165→4.48、MMA0.33→0.385。shader去shared是真实改变、寄存器24/20→32/24，端到端对v28仅0.4276%，不能以这些counter替代稳定时延收益或消除其他case正差。OOM8→10原失败保留，恢复采样后10不变，仍不证明内存风险解除。\n\n## 7. 实验总结')
f.write_text(body);assert body.count("## ")==7;print("report closed",74+4*n,194+12*n)
