from pathlib import Path
import hashlib,json,csv,subprocess,datetime
root=Path('/root/tilelang-metax');p=root/'race_tests/nsa';v='v101_worker1_s2_fixed_selection_sc-16g-2';r=p/'rep'/v
sha='e828f662199cccd32462389402776145390a96083f5748c649c0039b677c79f2';parent='4c674c79e4128f3c9f233fa6694c1a8f825d1048293accd9250fb5e2d86472b0';base='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
for f,digest in [(p/'submission.py',base),(p/'submission/v084_codex_power_s1_d32_d128_pair_sc-16g-2/submission.py',parent),(p/'submission'/v/'submission.py',sha),(Path('/tmp/nsa_power_v101_direct_qk.py'),sha)]:assert hashlib.sha256(f.read_bytes()).hexdigest()==digest
for name in ['parent_profile','parent_resources','initial_static','precompile','precompile_resources','precompile_static','precompile_stage','archive_static']:assert (r/(name+'.exit')).read_text().strip()=='0',name
for name in ['target_case10','target_screen']:assert (r/(name+'.exit')).read_text().strip()=='137'
assert not (r/'target_native_rows_gate.exit').exists();assert not (r/'formal_all14.exit').exists()
assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
rows=list(csv.DictReader((r/'target_case10_sc-16g-2.csv').open()));assert len(rows)==12 and all(x['status']=='PASS' for x in rows);chosen=[x for x in rows if x['variant']=='power_v101'];assert len(chosen)==4 and {x['case'] for x in chosen}=={'10'}
info=json.loads((r/'target_case10_codegen.json').read_text());assert len(info['records'])==3
for x in info['records']:assert hashlib.sha256(Path(x['device_path']).read_bytes()).hexdigest()==x['device_sha256'] and Path(x['host_path']).exists()
assert next(x['device_sha256'] for x in info['records'] if x['variant']=='power_v101')==json.loads((r/'precompile_codegen.json').read_text())['records'][0]['device_sha256']
owned={(r/name).read_text().strip() for name in ['preprobe.pid','preprobe_sampler.pid','precompile.pid','target_screen.pid']};ps=subprocess.check_output(['ps','-eo','pid,ppid,pgid,comm'],text=True).splitlines();assert not [x for x in ps[1:] if x.split()[0] in owned or x.split()[1] in owned or x.split()[2] in owned]
manifest={'version':v,'worker':'worker1','status':'failed_runtime_OOM_screen_inconclusive','closed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_sha256':sha,'parent_sha256':parent,'main_sha256':base,'start':json.loads((r/'start_identity.json').read_text()),'source_identity':json.loads((r/'source_identity.json').read_text()),'raw_failed_screen':json.loads((r/'failed_screen_summary.json').read_text()),'reference_count_scope':json.loads((r/'reference_count_scope.json').read_text()),'parent_profile':json.loads((r/'parent_profile_metrics.json').read_text()),'parent_resources':json.loads((r/'parent_resources.json').read_text()),'candidate_precompile_resources':json.loads((r/'precompile_resource_gate.json').read_text()),'actual_generated_mechanism':json.loads((r/'precompile_mechanism_observations.json').read_text()),'runtime_final':json.loads((r/'runtime_final.json').read_text()),'shared_inputs':json.loads((r/'shared_inputs_identity.json').read_text()),'initial_screen_exit':137,'failed_gate_unchanged':True,'automatic_approval_rejected_native_pass_gate':True,'native_metadata_retries':0,'candidate_profile':'not collected after failed gate','full14':False,'OJ':'no v101 scores','promotion':'none; failed archive only; main originalv28 unchanged'}
(r/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
for d in ['experiments','hack','rep','submission']:(p/d/v/'.gitattributes').write_text('* -text -eol -diff\n*.patch -diff\n')
files=[f for d in ['experiments','hack','rep','submission'] for f in (p/d/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];index={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(index,indent=2)+'\n');assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in index.items())
assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((p/d/v).relative_to(root)) for d in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True)
staged=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('failedclosed/staged',len(staged),'files; observedPASSrecords4/12; originalscreen137 retained')
