from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v121_worker1_c12_two_warp_selected_partition_sc-16g-2';r=b/'rep'/v;m=json.loads((r/'compile_source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());rt=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert not d['complete'] and len(d['all_jobs'])==2 and d['metadata_pairs']==2 and d['all_jobs'][0]['actual_exit']==0 and d['all_jobs'][1]['actual_exit']==1;assert all(x=='1' for x in rt['actual_waits'].values()) and rt['all_self_jobs_terminal'] and rt['OOM_values']==[13];assert not (r/'SDK').exists();assert (r/'static_parent113.exit').read_text().strip()=='0' and not (r/'static_candidate121.exit').exists();assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for k,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document']),('parentCPP',m['parent_C12_device'])]:assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],k
for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
for x in json.loads((r/'metadata_pair.json').read_text())['records']:
 for k in ['device','host']:assert sha(x[k+'_path'])==x[k+'_SHA']
assert sha(b/'submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd';assert sha(b/'experiments'/v/'candidate.py')=='be7566ae3fc67c278c62f356cf051f11732ed3b2e8899a76b405153e1c4b100c';assert sha(b/'experiments'/v/'candidate_rev02.py')==m['sources']['candidate121']['sha256']
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'failed_codegen_geometry_and_crosswarp_shared_alias_risk_no_native','source_reference':m['sources']['candidate121'],'old_rev01_unexecuted_source_kept':True,'original_runtime_result':d,'runtime_final':rt,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'actual_shared_alias_risk':json.loads((r/'actual_shared_alias_risk.json').read_text()),'geometry_actual10368_not_expected10496_gate1_retained':True,'no_resource_IR_native_recovery':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
files=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f','--']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(p0+'/') for p0 in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V121_FAILED_CLOSURE_STAGED',len(staged),len(idx),'0outside')
