from pathlib import Path
import json,hashlib,subprocess,datetime,csv
root=Path('/root/tilelang-metax');p=root/'race_tests/nsa';v='v108_worker1_reallocated_memory_budget_all14_sc-16g-2';r=p/'rep'/v;m=json.loads((r/'source_manifest.json').read_text());d=json.loads((r/'diagnostic_result.json').read_text());assert (r/'diagnostic.exit').read_text().strip()=='0' and d['runtime_protocol_completed'] and d['spawned_native_processes']==12 and d['observed_candidate_fullrefs']==56 and d['observed_inclusive_fullrefs']==168 and d['clean_candidate_fullrefs']==56 and d['clean_inclusive_fullrefs']==168 and all(j['native_exit']==0 and j['clean_process_accepted'] for j in d['all_jobs']);assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13 and not d['owned_live_at_end'];assert (r/'report_sc-16g-2.md').read_text().count('## ')==7;assert not (p/'submission'/v/'submission.py').exists()
for x in list(m['sources'].values())+list(m['tools'].values()):assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
assert (p/'rep/v104_worker1_s8_global_softmax_sc-16g-2/formal/diagnostic.exit').read_text().strip()=='1' and (p/'rep/v101_worker1_s2_fixed_selection_sc-16g-2/target_screen.exit').read_text().strip()=='137';assert subprocess.run(['kill','-0',(r/'master.pid').read_text().strip()],capture_output=True).returncode!=0
for j in d['all_jobs']:
 rows=list(csv.DictReader(Path(j['CSV']).open()));assert rows==j['rawCSVrows'] and len(rows)==14 and [int(x['case']) for x in rows]==list(range(1,15)) and all(x['status']=='PASS' for x in rows)
manifest={'version':v,'status':'completed_fixed_native_all14_C12_improved_positive_parent_deltas_retained','closed_UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_source_v104_sha256':m['sources']['power_v104']['sha256'],'source_manifest':m,'actual_result':d,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'runtime_final':json.loads((r/'runtime_final.json').read_text()),'all14_summary':json.loads((r/'all14_summary.json').read_text()),'old_v1041_v101137_preserved':True,'no_adaptive_retry_or_loosening':True,'kernel_source_changes':0,'native_processes':12,'observed_and_clean56C168inclusive':True,'full14_native_completed':True,'OJ':None,'main_promotion':False};(r/'manifest.json').write_text(json.dumps(manifest,indent=2)+chr(10))
for a in ['experiments','hack','rep','submission']:(p/a/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for a in ['experiments','hack','rep','submission'] for f in (p/a/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];index={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(index,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in index.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((p/a/v).relative_to(root)) for a in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V108_CLOSED_STAGED',len(staged),len(index),'observed=clean56C/168inclusive, positive deltas retained')
