from pathlib import Path
import csv,hashlib,json,subprocess,datetime
root=Path('/root/tilelang-metax');p=root/'race_tests/nsa';v='v072_codex_power_s1_two_query_waves_sc-16g-2';r=p/'rep'/v;sha='40bb24ef1bc16d022ec910f27b2ce876dd5a7a2b686313c3fff961171c0c9b6f';base='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
for f in [p/'submission'/v/'submission.py',Path('/tmp/nsa_power_v072_proven_bounds.py')]:assert hashlib.sha256(f.read_bytes()).hexdigest()==sha
assert hashlib.sha256((p/'submission.py').read_bytes()).hexdigest()==base
assert hashlib.sha256((p/'submission/v068_codex_power_s8_final_den_reduce_sc-16g-2/submission.py').read_bytes()).hexdigest()=='589d4ca2c5f82f97581cfb3f82eca96ad81c4c49b8624c60326eac0e34b14949'
assert hashlib.sha256((p/'submission/v064_codex_power_s8_serial_loop_sc-16g-2/submission.py').read_bytes()).hexdigest()=='575f2fa041acbfc1bf339f41b30f203d8b8f743ad2fded576a0db43da61beb67'
for n in ['codegen','oj_static','case6.resource','llvm_compile','llvm_dis','screen','paired_case6']:assert (r/(n+'.exit')).read_text().strip()=='0',n
for name,count in [('screen_case6_sc-16g-2.csv',1),('paired_case6_sc-16g-2.csv',12)]:
 rows=list(csv.DictReader((r/name).open()));assert len(rows)==count and all(x['status']=='PASS' for x in rows)
assert not json.loads((r/'machine_text_comparison.json').read_text())['text_sections_identical']
assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
owned={'132521','132742','132743','133223'};ps=subprocess.check_output(['ps','-eo','pid,pgid,comm'],text=True).splitlines();assert not [x for x in ps[1:] if x.split()[0] in owned or x.split()[1] in owned]
manifest={'version':v,'status':'rejected_target_regression_higher_MT','closed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'start':json.loads((r/'start_identity.json').read_text()),'source_sha256':sha,'main_sha256':base,'native_reference_checks':'13 selected C6 full naive_nsa PASS,W10/R50;no all14 correctness claim','paired':json.loads((r/'paired_summary.json').read_text()),'codegen':json.loads((r/'codegen_analysis.json').read_text()),'ownership':json.loads((r/'two_query_ownership_proof.json').read_text()),'AST_correspondence':json.loads((r/'two_wave_AST_correspondence.json').read_text()),'warp_API':json.loads((r/'warp_uniform_API_review.json').read_text()),'machine_text':json.loads((r/'machine_text_comparison.json').read_text()),'skipped':{'full14_risk_OJ':'target6.526percent slower,MT112/ST26,shared16KB;not promoted','mcProfiler_mcTracer':'clear target regression,freshv070 C6 profile referenced,not current72 data','ISA_decode':'unavailable;ELF section comparison is not disassembly','roofline':'actual sGPU roofs uncalibrated'},'cache':'code objects only,all attention content recomputed','promotion':'none;root v28 and pending64/68 unchanged','job_state':'known codegen/compiler/native groups terminal;no unowned kills'}
(r/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');(p/'submission'/v/'status.json').write_text(json.dumps({'status':manifest['status'],'archive_only':True,'sha256':sha,'source_checks':'13selected C6;no all14/OJ claim'},indent=2)+'\n')
for d in ['experiments','hack','rep','submission']:(p/d/v/'.gitattributes').write_text('* -text -eol -diff\n*.patch -diff\n')
files=[f for d in ['experiments','hack','rep','submission'] for f in (p/d/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];index={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(index,indent=2)+'\n');assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in index.items())
assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((p/d/v).relative_to(root)) for d in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True)
selected=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(selected)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in selected)
subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('closed and staged',len(selected),'files;commit separate')
