from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v120_worker1_existing_C6_original_native_screen_sc-16g-2';r=b/'rep'/v;n=r/'native_screen';m=json.loads((n/'native_source_manifest.json').read_text());d=json.loads((n/'diagnostic_result.json').read_text());s=json.loads((n/'screen_summary.json').read_text());runtime=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert d['runtime_protocol_completed'] and d['failure'] is None and len(d['all_jobs'])==12 and all(j['native_exit']==0 and j['clean_process_accepted'] for j in d['all_jobs']);assert d['observed_candidate_fullrefs']==d['clean_candidate_fullrefs']==4 and d['observed_inclusive_fullrefs']==d['clean_inclusive_fullrefs']==12
assert s['decision']=='rejected_latency' and not s['ranges_overlap'];assert all(x=='0' for x in runtime['actual_waits'].values()) and runtime['all_self_jobs_terminal'] and runtime['OOM_values']==[13];assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for label,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document'])]+[(k,m[k]) for k in ['existing_parent_C6_device','existing_candidate_C6_device','frozen_IR_observation','frozen_IR_actual_exit','preserved_resource_gate_exit']]:assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],label
for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
for f,item in json.loads((r/'raw_CSV_identity.json').read_text()).items():assert sha(f)==item['sha256']
assert Path(m['preserved_resource_gate_exit']['path']).read_text().strip()=='1';assert m['sources']['candidate_v118']['sha256']=='290ac7d13d219d161d14833fcfa777df6ae809982708bb6a95f1a4172a3acf2e'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'rejected_latency_vs_v084_original_C6_screen','source_reference':m['sources']['candidate_v118'],'original_runtime_result':d,'runtime_final':runtime,'summary':s,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'old118_MT90_gate1_retained':True,'other_source_impact':json.loads((r/'case_impact_scope.json').read_text()),'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
files=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];inventory={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(inventory,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in inventory.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f','--']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V120_CLOSURE_STAGED',len(staged),len(inventory),'12originalCSVSHA/0outside')
