from pathlib import Path
import ast,copy,json,hashlib,difflib
root=Path('/root/tilelang-metax');v='v212_worker2_c8_direct_k_operand_subagent2';r=root/'race_tests/nsa/rep'/v;x=root/'race_tests/nsa/experiments'/v
parent=root/'race_tests/nsa/submission/v084_codex_power_s1_d32_d128_pair_sc-16g-2/submission.py';s=parent.read_text();assert hashlib.sha256(s.encode()).hexdigest()=='4c674c79e4128f3c9f233fa6694c1a8f825d1048293accd9250fb5e2d86472b0';tree=ast.parse(s);base=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='_make_power_s1_case4_dense');n=copy.deepcopy(base);n.name='_make_worker2_c8_direct_k_operand'
def validbody(f):
 fn=next(z for z in f.body if isinstance(z,ast.FunctionDef) and z.name=='native_sparse_attention');sel=next(z for z in fn.body[0].body if isinstance(z,ast.For) and z.target.id=='selected');return sel.body[1].body
body=validbody(n);removed=copy.deepcopy(body[:3]);assert isinstance(removed[0],ast.Expr) and ast.unparse(removed[0])=='T.sync_warp()';assert isinstance(removed[1],ast.For) and removed[1].target.id=='part';assert ast.unparse(removed[2])=='T.sync_warp()'
body[:3]=[];chunk=next(z for z in body if isinstance(z,ast.For) and z.target.id=='chunk');element=chunk.body[0];oldassign=copy.deepcopy(element.body[0]);element.body[0]=ast.parse('k_local[element] = K[batch_id, block_start + lane % 16, kv_head, chunk * 16 + (lane // 16) * 4 + element]').body[0]
undo=copy.deepcopy(n);undo.name=base.name;ub=validbody(undo);uc=next(z for z in ub if isinstance(z,ast.For) and z.target.id=='chunk');uc.body[0].body[0]=oldassign;ub[:0]=removed;assert ast.dump(undo,include_attributes=False)==ast.dump(base,include_attributes=False)
ast.fix_missing_locations(n);helper=ast.unparse(n)+'\n';assert helper.count('T.sync_warp()')==5;key=(2,4096,1,16,64,1,16,True);candidate='# codex-power v212\n'+s.split('\n',1)[1]+'\n\n'+helper+'\n_power_install_lazy_code('+repr(key)+', '+n.name+')\n';p=Path('/tmp/nsa_worker2_v212_c8_direct_k_operand.py');p.write_text(candidate);t=ast.parse(candidate);assert len(t.body)==len(tree.body)+2 and ast.dump(ast.Module(t.body[:len(tree.body)],[]),include_attributes=False)==ast.dump(tree,include_attributes=False);assert ast.literal_eval(t.body[-1].value.args[0])==key
(x/'direct_k_operand_kernel.py').write_text(helper);(x/'source_diff.patch').write_text(''.join(difflib.unified_diff(s.splitlines(keepends=True),candidate.splitlines(keepends=True),fromfile=str(parent),tofile=str(p))))
i={'candidate_path':str(p),'candidate_sha256':hashlib.sha256(candidate.encode()).hexdigest(),'parent_sha256':hashlib.sha256(s.encode()).hexdigest(),'factory_name':n.name,'dispatch_key':list(key),'official_case_number':8,'prefix_14_AST_nodes_equal':True,'inverse_Kproducer_presync_postsync_and_Kassignment_wholefactory_AST_equal':True,'only_K_stage_changes':True,'Num16_Q_PV_Pden_math_guard_literalunchanged':True,'K_read_source':ast.unparse(element.body[0]),'K_vectorized_half_elements':4,'original_K_global_perlane_vectors':[2,16],'direct_K_perlane_vectors':[4,8],'fullvalid_source_sync_sites':5,'kept_preV_sync_protects_Qsharedread_to_Voverwrite':True,'Qpost_Vpost_Outputpre_Outputpost_unchanged':True,'MMA8_shfl4_expected_not_compiled':True,'exact_import_count':len([z for z in t.body if isinstance(z,(ast.Import,ast.ImportFrom))]),'new_import_compile_profile_native':[0,0,0,0]};assert i['exact_import_count']==3;(r/'source_identity.json').write_text(json.dumps(i,indent=2)+'\n');print(json.dumps(i,indent=2))
