from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v122_worker1_c12_explicit_reduction_slots_sc-16g-2';r=b/'rep'/v;n=r/'native_screen';cm=json.loads((r/'compile_source_manifest.json').read_text());nm=json.loads((n/'native_source_manifest.json').read_text());c=json.loads((r/'stage_result.json').read_text());d=json.loads((n/'diagnostic_result.json').read_text());s=json.loads((n/'screen_summary.json').read_text());rt=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert c['complete'] and len(c['all_jobs'])==5 and all(x['actual_exit']==0 for x in c['all_jobs']);assert d['runtime_protocol_completed'] and len(d['all_jobs'])==12 and all(j['native_exit']==0 and j['clean_process_accepted'] for j in d['all_jobs']);assert d['observed_candidate_fullrefs']==d['clean_candidate_fullrefs']==4 and d['observed_inclusive_fullrefs']==d['clean_inclusive_fullrefs']==12;assert s['decision']=='rejected_latency' and not s['ranges_overlap'];assert rt['all_self_jobs_terminal'] and rt['OOM_values']==[13];assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for m in [cm,nm]:
 for k,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document'])]:assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],k
 for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
for x in json.loads((r/'metadata_pair.json').read_text())['records']:
 for k in ['device','host']:assert sha(x[k+'_path'])==x[k+'_SHA']
for f,x in json.loads((r/'raw_CSV_identity.json').read_text()).items():assert sha(f)==x['sha256']
assert (b/'rep/v121_worker1_c12_two_warp_selected_partition_sc-16g-2/stage.exit').read_text().strip()=='1';assert sha(b/'experiments'/v/'candidate.py')==sha(b/'submission'/v/'submission.py')=='88bd3007df4a5173fec5de7c0471ac4d8462e1f44269c1c2ee2fae9cd60aca01';assert sha(b/'submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'rejected_latency_vs_best_CB13_after_actual_shared_alias_fix','source_reference':nm['sources']['candidate_v122'],'compile':c,'native':d,'summary':s,'runtime_final':rt,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'actual_shared':json.loads((r/'actual_shared_materialization.json').read_text()),'old121failedgate1_preserved':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
files=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f','--']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(z+'/') for z in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V122_CLOSURE_STAGED',len(staged),len(idx),'12CSVbyteSHA/0outside')
