from pathlib import Path
import ast,hashlib,json
p=Path('/root/tilelang-metax/race_tests/nsa');v='v082_codex_power_s1_d128_dense_sc-16g-2';old=p/'experiments/v079_codex_power_s1_case4_dense_sc-16g-2/s1_case4_kernel.py';s=old.read_text();assert hashlib.sha256(old.read_bytes()).hexdigest()=='bb4584c7465185a088e85d43f51baafeffb47971871463f7a173b3158d8defdf'
s=s.replace('# codex-power v079','# codex-power v082',1).replace('_make_power_s1_case4_dense','_make_power_s1_d128_dense',1).replace('dim == 64','dim == 128',1)
a=ast.parse(s);fn=next(x for x in a.body if isinstance(x,ast.FunctionDef));defs=[x for x in fn.body if isinstance(x,ast.FunctionDef) and x.name in ['qk_slot','out_slot','v_slot']];newdefs={
'qk_slot':"    def qk_slot(row, col):\n        lo = col % 64\n        return row * 128 + (col // 64) * 64 + ((lo // 8) ^ (row % 8)) * 8 + (((lo // 4) % 2) ^ ((row // 8) % 2) ^ (row % 2)) * 4 + lo % 4\n",
'out_slot':"    def out_slot(row, col):\n        lo = col % 64\n        return row * 128 + (col // 64) * 64 + ((lo // 8) ^ (row % 8)) * 8 + (((lo // 4) % 2) ^ ((row // 8) % 2)) * 4 + lo % 4\n",
'v_slot':"    def v_slot(row, col):\n        lo = col % 64\n        return (col // 64) * 1024 + ((lo // 4 + 16 * (lo % 4)) ^ ((row // 4) % 2)) * 16 + ((row // 4) ^ (lo // 16) ^ (lo % 4)) * 4 + row % 4\n"}
lines=s.splitlines(True)
for x in sorted(defs,key=lambda x:x.lineno,reverse=True):lines[x.lineno-1:x.end_lineno]=[newdefs[x.name]]
s=''.join(lines).replace('T.alloc_shared([1024]','T.alloc_shared([2048]').replace('q_local = T.alloc_local(16','q_local = T.alloc_local(32').replace('numerator = T.alloc_local(16','numerator = T.alloc_local(32').replace('v_operand = T.alloc_local(16','v_operand = T.alloc_local(32').replace('for part in T.unroll(2)','for part in T.unroll(4)').replace('for chunk in T.unroll(4)','for chunk in T.unroll(8)').replace('pos // 64','pos // 128').replace('pos % 64','pos % 128')
start=s.index('                    fetch_row =');end=s.index('                    T.sync_warp()',start);block=s[start:end];block=block.replace('fetch_col = (lane % 8) * 8','fetch_col = panel * 64 + (lane % 8) * 8');s=s[:start]+'                    for panel in T.unroll(2):\n'+''.join('    '+line for line in block.splitlines(True))+s[end:];ast.parse(s);dest=p/'experiments'/v/'s1_d128_kernel.py';dest.write_text(s);(p/'rep'/v/'helper_identity.json').write_text(json.dumps({'new_source_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'coordinate_design':'two64feature panels; qk/out interleaved row128, V panel1024half offsets','old_own79_hash':hashlib.sha256(old.read_bytes()).hexdigest(),'original_team_kernels_not_read':True,'changes':'4load/store parts,8feature MFMA chunks,q/num/Vop32, shared2048half,S1D128BS16 only'},indent=2)+'\n');print('new D128 helper',dest)
