from pathlib import Path
from decimal import Decimal
import json,statistics
p=Path('/root/tilelang-metax/race_tests/nsa');v='v082_codex_power_s1_d128_dense_sc-16g-2';r=p/'rep'/v;formal=json.loads((r/'formal_all14_summary.json').read_text());risk=json.loads((r/'risk_summary.json').read_text());prof=json.loads((r/'mcprof_summary.json').read_text());resources=json.loads((r/'resource_summary.json').read_text());f=r/'report_sc-16g-2.md';body=f.read_text().split('## 5.')[0]
body+='## 5. Benchmark\n\nOriginal full naive_nsa, F16 causal seed0, W10R50 and tolerance unchanged. B-I-C-C-I-B twice,4 samples/source. Unit us. Every initial and fixed-confirmation sample retained, no byte-identity waiver.\n\n| case | v28 | parent81 | v082 | vs v28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in formal['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v082']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
body+='\nFixed confirmation of EVERY positive formal delta versus original or parent,once only.\n\n| case | v28 | parent81 | v082 | vs v28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in risk['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v082']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
n=len(risk['cases']);body+='\nExact candidate checks {} across14cases; whole experiment {} includingcontrols. Target4/12,formal56/168,risk{}/{},exactarchive14/14. Count merged files only,percase copies/metadata/profile calls not extra references.\n'.format(74+4*n,194+12*n,4*n,12*n)
body+='\n## 6. Profile\n\nFresh parent preprobe and postnative current paired mcProfiler case3 counts2/source.256waves/1MiB scope consistency necessary,not exclusive. DriverW10+20 requires_grad=False,native=True; no runtime-equivalence claim.\n\n| metric mean | parent81 | v082 |\n|---|---:|---:|\n'
for k in ['waves','read_bytes','write_bytes','l2_hit_pct','shared_nonconflict_pct','conflict_cycles','load_latency_cycles','mte_pct','mma_pct']:
 vals=[]
 for label in ['parent_v081','power_v082']:
  xs=[x[k] for x in prof if x['variant']==label and x[k] is not None];vals.append('{:.4f}'.format(statistics.mean(xs)) if len(xs)==2 else 'unavailable')
 body+='| '+k+' | '+vals[0]+' | '+vals[1]+' |\n'
body+='\n| source | MT | ST | stackB | dynamic sharedB | static maxwarps/PEU |\n|---|---:|---:|---:|---:|---:|\n'
for x in resources:body+='| {} | {} | {} | {} | {} | {} |\n'.format(x['variant'],x['MT'],x['ST'],x['stack_bytes'],x['dynamic_shared_bytes_host'],x['static_max_warps_per_PEU'])
body+='\nStatic shared0 doesnot mean total0,actual host dynamic shared is captured. Static maxwarps/raw achieved waves are not measured occupancy; minblocks warning kept. No working ISA decoder or calibrated actual sGPU roofs; mcTracer prior124/header-only not retried. mx-smi read-only summaries not perkernel bandwidth/occupancy.\n\n## 7. Conclusion\n\nSingle C3 dispatch added; other13 bodies/keys exactparent81. Full14 native correctness passes. Preserve every positive formal/risk difference; external OJ scores pending,no no-regression proof. Inconclusive archive only,main exactv28,prior candidates unchanged. Actual resource/profile and native latency must be interpreted together; no bank-only causal attribution.\n'

for before,after in {'## 5. Benchmark': '## 5. Benchmark 对比', '## 6. Profile': '## 6. Profile 指标变化', '## 7. Conclusion': '## 7. 实验总结', 'Original full naive_nsa, F16 causal seed0, W10R50 and tolerance unchanged. B-I-C-C-I-B twice,4 samples/source. Unit us. Every initial and fixed-confirmation sample retained, no byte-identity waiver.': '原始完整naive_nsa、F16 causal seed0、W10R50/容差不变。B-I-C-C-I-B两轮，各4样本，单位us。首轮与固定复测全保留，不以字节一致豁免时延。', 'Fixed confirmation of EVERY positive formal delta versus original or parent,once only.': '首轮相对任一对照出现正差的全部case固定复测一次。', 'Exact candidate checks': '精确候选参考次数', 'across14cases; whole experiment': '覆盖14项；全组', 'Count merged files only,percase copies/metadata/profile calls not extra references.': '只计合并文件，逐case副本、metadata/profile不重复计完整参考。', 'Fresh parent preprobe and postnative current paired mcProfiler case3 counts2/source.256waves/1MiB scope consistency necessary,not exclusive. DriverW10+20 requires_grad=False,native=True; no runtime-equivalence claim.': '先fresh parent preprobe，native结束后再当前双版本mcProfiler各2样本。256waves/1MiB scope一致仅必要条件。driverW10+20 requires_grad=False，native=True，不宣称运行时等价。', 'Static shared0 doesnot mean total0,actual host dynamic shared is captured. Static maxwarps/raw achieved waves are not measured occupancy; minblocks warning kept. No working ISA decoder or calibrated actual sGPU roofs; mcTracer prior124/header-only not retried. mx-smi read-only summaries not perkernel bandwidth/occupancy.': '静态shared0不是总量0，动态shared取实际host；static maxwarps/raw achieved不是实测占用，保留minblocks警告。没有可用ISA解码器或已标定sGPU roof；mcTracer前期124/仅header，本版未重试。mx-smi仅只读状态，不是逐kernel带宽/占用。', 'Single C3 dispatch added; other13 bodies/keys exactparent81. Full14 native correctness passes. Preserve every positive formal/risk difference; external OJ scores pending,no no-regression proof. Inconclusive archive only,main exactv28,prior candidates unchanged. Actual resource/profile and native latency must be interpreted together; no bank-only causal attribution.': '仅新增C3，其余13个body/keys精确parent81。全14 native正确性通过，正式/风险所有正差保留；外部OJ分数待核对，无退化尚未证明。本版rejected：case1固定确认相对原始v28 +5%、相对parent81 +5.154%，未通过本地无退化门槛；只归档候选，主入口原v28与此前候选不变。结合实际资源/profile/端到端判断，不把收益全归因bank冲突。'}.items():body=body.replace(before,after)
body=body.replace('## 7. 实验总结','缓存host结构只读AST审计：run_kernel已有key/get/if-miss/call快速路径，class仅在miss分支，未发现每call重复定义class；因此不据此另改host。GPU代码一致不解释也不豁免case1 +5%，剩余时延来源未验证。\n\n## 7. 实验总结')
body=body.replace('## 7. 实验总结','当前双版本C3计数：shared35.275%→80.49%、conflict7.145→0.89，MTE10.46→12.905、MMA1.495→1.915；但load43.83→50.785变差、L2 56.505→55.78略降、流量近似相同。shared8→4KiB、MT52→66、static maxwarps8→7。端到端目标改善16.202%，指标支持布局/供给变化，不能据单计数断言唯一瓶颈或实际占用变好。case1固定+5%是独立退化门槛失败，不因C3收益或上述指标豁免。\n\n## 7. 实验总结')
f.write_text(body);assert body.count("## ")==7;print("report closed",74+4*n,194+12*n)
