from pathlib import Path
from decimal import Decimal
import json,statistics
p=Path('/root/tilelang-metax/race_tests/nsa');v='v084_codex_power_s1_d32_d128_pair_sc-16g-2';r=p/'rep'/v;formal=json.loads((r/'formal_all14_summary.json').read_text());risk=json.loads((r/'risk_summary.json').read_text());prof=json.loads((r/'mcprof_summary.json').read_text());resources=json.loads((r/'resource_summary.json').read_text());f=r/'report_sc-16g-2.md';body=f.read_text().split('## 5.')[0]
body+='## 5. Benchmark\n\nOriginal fullnaive_nsa,F16 causal seed0,W10R50/tolerance unchanged. B-I-C-C-I-B twice,4samples/source. Unitus,all initial and fixedconfirmation values preserved; no identity/noise waiver.\n\n| case | v28 | parent81 | v084 | vsv28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in formal['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v084']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
body+='\nFixedrisk for ALL positive formal deltas versus eithercontrol,once.\n\n| case | v28 | parent81 | v084 | vsv28 | vs81 |\n|---|---:|---:|---:|---:|---:|\n'
for x in risk['cases']:
 m=x['medians_us'];body+='| {} | {:.6f} | {:.6f} | {:.6f} | {:+.3f}% | {:+.3f}% |\n'.format(x['case'],Decimal(m['baseline_v28']),Decimal(m['parent_v081']),Decimal(m['power_v084']),Decimal(x['vs_v28_pct']),Decimal(x['vs_parent_pct']))
n=len(risk['cases']);body+='\nExact candidate fullreference checks{} across14cases; totalincludingcontrols{}. Target8/24,targetconfirmation4/12,formal56/168,risk{}/{},exactarchive14/14. Mergedfiles countonce; percase copies/metadata/profile notextra reference calls.\n'.format(82+4*n,218+12*n,4*n,12*n)
body+='\n## 6. Profile\n\nCurrent paired mcProfiler C1/C3 counts2/source AFTERnative,driverW10+20 gradFalse versusnativeTrue,not runtimeequivalence proof. Scope64waves/64KiB and256waves/1MiB plus predeclared0to512unattributed residual,necessary notexclusive. WGload latency isWorkgroup Memory,notglobal/DRAM. C1no WGaccess reported100/0 isnot usableefficiency or globalzero.\n\n| case/metric mean | parent81 | v084 |\n|---|---:|---:|\n'
for ci in [1,3]:
 for k in ['waves','read_bytes','write_bytes','l2_hit_pct','shared_nonconflict_pct','conflict_cycles','WG_load_latency_cycles','mte_pct','mma_pct']:
  values=[]
  for label in ['parent_v081','power_v084']:
   xs=[x[k] for x in prof if x['case']==ci and x['variant']==label and x[k] is not None];values.append('{:.4f}'.format(statistics.mean(xs)) if len(xs)==2 else 'unavailable')
  body+='| {}/{} | {} | {} |\n'.format(ci,k,*values)
body+='\n| case/source | MT | ST | stackB | dynamicsharedB | static maxwarps/PEU |\n|---|---:|---:|---:|---:|---:|\n'
for x in resources:body+='| {}/{} | {} | {} | {} | {} | {} |\n'.format(x['case'],x['variant'],x['MT'],x['ST'],x['stack_bytes'],x['dynamic_shared_bytes_host'],x['static_max_warps_per_PEU'])
body+='\nStatic/dynamicshared distinguished viaactualhost. maxwarps/raw achieved not measuredoccupancy. No exclusive bank attribution,no workingISAdecode/calibratedsGPUroof,prior mcTracer124/header-only no freshtimeline. mx-smi runtime summaries notperkernel bandwidth.\n\n## 7. Conclusion\n\nNew combination adds only C1/C3;other12 math/keys exact81. Full14 correctness passes; all screen/confirmation/formal/risk positives retained. ExternalOJ pending,strictno-regression unproved; archiveonly,originalv28 main and priorcandidates unchanged. Actualnative/profile/resource jointly interpreted,priorfailedversions notwaived.\n'

for before,after in {'## 5. Benchmark': '## 5. Benchmark 对比', '## 6. Profile': '## 6. Profile 指标变化', '## 7. Conclusion': '## 7. 实验总结', 'Original fullnaive_nsa,F16 causal seed0,W10R50/tolerance unchanged. B-I-C-C-I-B twice,4samples/source. Unitus,all initial and fixedconfirmation values preserved; no identity/noise waiver.': '原始完整naive_nsa/F16 causal/seed0/W10R50/容差不变，B-I-C-C-I-B两轮各4样本，单位us。所有首轮和固定确认数据保留，不以字节一致或噪声猜测豁免。', 'Fixedrisk for ALL positive formal deltas versus eithercontrol,once.': '正式相对任一控制正差的全部case固定复测一次。', 'Exact candidate fullreference checks': '精确候选完整参考次数', 'across14cases; totalincludingcontrols': '覆盖14项；含对照全组', 'Mergedfiles countonce; percase copies/metadata/profile notextra reference calls.': '合并仅计一次，逐case副本/metadata/profile不是额外参考。', 'Current paired mcProfiler C1/C3 counts2/source AFTERnative,driverW10+20 gradFalse versusnativeTrue,not runtimeequivalence proof. Scope64waves/64KiB and256waves/1MiB plus predeclared0to512unattributed residual,necessary notexclusive. WGload latency isWorkgroup Memory,notglobal/DRAM. C1no WGaccess reported100/0 isnot usableefficiency or globalzero.': 'native结束后当前双目标mcProfiler各source2样本，driverW10+20 gradFalse/nativetrue，不宣称运行时等价。64waves/64KiB与256waves/1MiB加事先定义0–512B未归因残量，仅必要scope一致性。WG-load是Workgroup Memory，不是global/DRAM；C1零访问工具100/0不当有效效率或global零延迟。', 'Static/dynamicshared distinguished viaactualhost. maxwarps/raw achieved not measuredoccupancy. No exclusive bank attribution,no workingISAdecode/calibratedsGPUroof,prior mcTracer124/header-only no freshtimeline. mx-smi runtime summaries notperkernel bandwidth.': '静/动态shared分开并核验实际host。maxwarps/raw achieved不是实测占用，不把所有收益归因bank；无ISA解码器/已标定sGPU roof，前期mcTracer124/仅header未新重试。mx-smi状态不是逐kernel带宽。', 'New combination adds only C1/C3;other12 math/keys exact81. Full14 correctness passes; all screen/confirmation/formal/risk positives retained. ExternalOJ pending,strictno-regression unproved; archiveonly,originalv28 main and priorcandidates unchanged. Actualnative/profile/resource jointly interpreted,priorfailedversions notwaived.': '组合仅新C1/C3，其他12项math/keys精确81。全14正确性通过，screen/一次确认/正式/风险所有正差保留。用户提供v84截图显示对原v28全14分数非退化、13项严格提高；截图与源码关联按用户版本说明，上传SHA未独立核验。相对81的本地正差保留，81的OJ分数未提供。仅归档，main原v28与此前候选保持。结合实际native/profile/resource，不豁免以前失败。'}.items():body=body.replace(before,after)
f.write_text(body);assert body.count("## ")==7;print("report closed",82+4*n,218+12*n)
