from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v126_worker1_fresh_case6_baseline_counter_sc-16g-2';r=b/'rep'/v;m=json.loads((r/'source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());rt=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert d['complete'] and len(d['all_jobs'])==1 and d['all_jobs'][0]['actual_exit']==0 and d['actual_counter_records']==d['valid_scope_records']==2;assert rt['all_self_jobs_terminal'] and rt['OOM_values']==[13] and all(x=='0' for x in rt['outerwaits'].values()) and rt['SDKwait']['actual_CLI_waitcode']==0;assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for k,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document'])]+list(m['reused_artifacts'].items()):assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],k
for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
assert sha(b/'submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd';assert (b/'rep/v117_worker1_reused_C6_C10_parent_resource_profile_sc-16g-2/stage.exit').read_text().strip()=='1'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'finite_exact_C6_profile_completed_no_bottleneck_claim','runtime':d,'runtime_final':rt,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'resource_reuse':json.loads((r/'existing_C6_identity_reuse.json').read_text()),'review_display_mistake_notcodebug':True,'source_kernelunchanged':True,'old117gate1_preserved':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
allfiles=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];files=[f for f in allfiles if '__pycache__' not in f.parts and f.suffix!='.pyc'];excluded=[str(f.relative_to(root)) for f in allfiles if f not in files];(r/'generated_cache_excluded.json').write_text(json.dumps({'files_excluded_notdeleted':excluded,'no_closed_history_rewrite':True},indent=2)+chr(10));files.append(r/'generated_cache_excluded.json');idx={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];exact=list(idx)+[str((r/'archive_sha256.json').relative_to(root))];subprocess.run(['git','add','-f','--']+exact,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert sorted(staged)==sorted(exact) and all(any(f.startswith(z+'/') for z in paths) for f in staged);assert not any('__pycache__' in f or f.endswith('.pyc') for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V126_CLOSURE_STAGED',len(staged),len(idx),'excludedcache',len(excluded),'raw2/0outside')
