from pathlib import Path
import hashlib,json,csv,subprocess,datetime
from decimal import Decimal
root=Path('/root/tilelang-metax');p=root/'race_tests/nsa';v='v104_worker1_s8_global_softmax_sc-16g-2';r=p/'rep'/v;sha='27f6021b1edcdd3d48d8f8e7b0182492b8a3607b6ce0e7e28c8097bd6ec20e07';parent='4c674c79e4128f3c9f233fa6694c1a8f825d1048293accd9250fb5e2d86472b0';base='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
for f,h in [(p/'submission.py',base),(p/'submission/v084_codex_power_s1_d32_d128_pair_sc-16g-2/submission.py',parent),(p/'submission'/v/'submission.py',sha),(Path('/tmp/nsa_power_v104_global_softmax.py'),sha)]:assert hashlib.sha256(f.read_bytes()).hexdigest()==h
assert (p/'submission'/v/'submission.py').read_text().splitlines()[0]=='# codex-power v104'
for n in ['initial_static','precompile','precompile_resources','precompile_resource_command','precompile_static','precompile_stage','optimized_IR_capture','archive_static','diagnostic']:assert (r/(n+'.exit')).read_text().strip()=='0',n
assert (r/'formal/diagnostic.exit').read_text().strip()=='1';formal=json.loads((r/'formal/diagnostic_result.json').read_text());assert not formal['runtime_protocol_completed'] and len(formal['all_jobs'])==141;last=formal['all_jobs'][-1];assert last['index']==141 and last['native_exit']==-9 and last['observed_PASS_records']==0 and last['cgroup_before']['oom_kill']==11 and last['cgroup_after']['oom_kill']==13
assert (p/'rep/v101_worker1_s2_fixed_selection_sc-16g-2/target_screen.exit').read_text().strip()=='137';assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
shared=json.loads((r/'shared_inputs_identity.json').read_text())['files']
for f,h in shared.items():assert hashlib.sha256((root/f).read_bytes()).hexdigest()==h,f
screen=json.loads((r/'diagnostic_result.json').read_text());assert screen['runtime_protocol_completed'];cand=total=0;owned=set()
for result in [screen,formal]:
 for job in result['all_jobs']:
  owned.update([str(job['pid']),str(job['pgid'])]);f=Path(job['csv']);rows=list(csv.DictReader(f.open())) if f.exists() else [];assert rows==job['records']
  for row in rows:
   assert row['status']=='PASS' and int(row['case'])==job.get('case',12) and Decimal(row['latency_ms'])>0;total+=1;cand+=job['variant']=='power_v104'
assert cand==50 and total==152
for f in r.rglob('*.pid'):
 if f.read_text().strip().isdigit():owned.add(f.read_text().strip())
ps=subprocess.check_output(['ps','-eo','pid,ppid,pgid,state,comm'],cwd=root,text=True).splitlines();alive=[x for x in ps[1:] if (x.split()[0] in owned or x.split()[1] in owned or x.split()[2] in owned) and x.split()[3]!='Z'];assert not alive,alive
for stage in ['risk','metadata_all14','paired_profile']:assert not (r/stage/'launch_once.lock').exists()
assert not (r/'final_resources').exists()
runtime=json.loads((r/'runtime_final.json').read_text());assert runtime['all_self_started_jobs_terminal'] and runtime['formal_exit']==1 and runtime['OOM_after']==13;counts=json.loads((r/'reference_count_scope.json').read_text());assert counts['candidate_total_full_refs']==50 and counts['inclusive_total_full_refs']==152
manifest={'version':v,'status':'failed_runtime_OOM_formal_incomplete','closed_UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_source_sha256':sha,'parent_source_sha256':parent,'main_source_sha256':base,'source_identity':json.loads((r/'source_identity.json').read_text()),'native_reference_counts':counts,'screen':json.loads((r/'target_screen_summary.json').read_text()),'formal_prefix':json.loads((r/'formal_failed_prefix_summary.json').read_text()),'runtime_final':runtime,'failure_memory_forensics':json.loads((r/'formal_failed_memory_forensics.json').read_text()),'readonly_current_census':'formal_failure_readonly_PID_census.json','compiler_resource_only':json.loads((r/'precompile_resource_gate.json').read_text()),'optimized_IR_only':json.loads((r/'optimized_IR_index_proof.json').read_text()),'source_safety_codegen_gate':json.loads((r/'actual_safety_and_width_gate.json').read_text()),'post_pipeline_blocked':json.loads((r/'post_pipeline_blocked.json').read_text()),'all_positive_delta_and_outlier_retained':True,'old_v101_exit137_preserved':True,'all14_completed':False,'no_regression_demonstrated':False,'OOM_cause_verified':False,'OJ':None,'main_promotion':False};(r/'manifest.json').write_text(json.dumps(manifest,indent=2)+chr(10))
for d in ['experiments','hack','rep','submission']:(p/d/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for d in ['experiments','hack','rep','submission'] for f in (p/d/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];index={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(index,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in index.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((p/d/v).relative_to(root)) for d in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('FAILED_CLOSED_STAGED',len(staged),'files',cand,total,'refs; no full14/promotion')
