from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v113_worker1_s4_global_softmax_sc-16g-2';r=b/'rep'/v;n=r/'native_screen';d=json.loads((n/'diagnostic_result.json').read_text());assert not d['runtime_protocol_completed'] and d['spawned_native_processes']==d['observed_inclusive_fullrefs']==d['clean_inclusive_fullrefs']==0;assert d['failure']=='wholeCG exceeds new4GiB admission';assert (n/'controller_actual.exit').read_text().strip()==(n/'native_supervisor_actual.exit').read_text().strip()=='1';assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13;assert (r/'compiled_gate_recovery01_actual.exit').read_text().strip()=='0' and (r/'compiled_gate.exit').read_text().strip()=='1';assert (r/'controller_actual.exit').read_text().strip()==(r/'supervisor_recovery01_actual.exit').read_text().strip()=='1';assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for source in ['experiments','submission']:assert hashlib.sha256((b/source/v/('candidate.py' if source=='experiments' else 'submission.py')).read_bytes()).hexdigest()=='cb30f2f7982c3415af53a5c137f5563ec849eed7fe85228a4b05384e6b1e1bcc'
assert hashlib.sha256((b/'submission.py').read_bytes()).hexdigest()=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
for name in ['metadata_source_manifest.json','native_screen/native_source_manifest.json']:
 m=json.loads((r/name).read_text())
 for x in list(m['sources'].values())+list(m['tools'].values())+[m['shared_identity_document'],m['existing_parent_C11_device']]:assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
for name,sha in json.loads((r/'shared_inputs_identity.json').read_text())['files'].items():assert hashlib.sha256((root/name).read_bytes()).hexdigest()==sha
for label in ['power_v104','power_v113']:
 data=json.loads((r/('metadata_'+label+'.json')).read_text());assert len(data['records'])==1 and data['records'][0]['case']==11 and data['NSA_attention_calls']==data['full_reference_checks']==0
 for x in data['records']:
  for k in ['device','host']:assert hashlib.sha256(Path(x[k+'_path']).read_bytes()).hexdigest()==x[k+'_sha256']
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'native_admission_refused_no_reference_or_latency','candidate_SHA':'cb30f2f7982c3415af53a5c137f5563ec849eed7fe85228a4b05384e6b1e1bcc','metadata_original7stage_failed_CPUparser':json.loads((r/'stage_result.json').read_text()),'CPUrecovery':json.loads((r/'compiled_gate_recovery01_wait.json').read_text()),'native_actual_refusal':d,'runtime_final':json.loads((r/'runtime_final.json').read_text()),'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'initial_failures_and_UNAVAILABLE_waits_preserved':True,'no_retry_or_changed_budget':True,'OJ':None,'main_promotion':False},indent=2)+chr(10))
for a in ['experiments','hack','rep','submission']:(b/a/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for a in ['experiments','hack','rep','submission'] for f in (b/a/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==sha for f,sha in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((b/a/v).relative_to(root)) for a in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('V113_CLOSED',len(staged),len(idx),'native0refs,failed4GiBadmission')
