from pathlib import Path
import ast,json,hashlib
root=Path('/root/tilelang-metax');v='v113_worker1_s4_global_softmax_sc-16g-2';r=root/'race_tests/nsa/rep'/v;m=json.loads((r/'source_manifest.json').read_text());bp=Path(m['base104']['path']);cp=Path(m['candidate113']['path']);bs=bp.read_text();cs=cp.read_text();assert hashlib.sha256(bp.read_bytes()).hexdigest()==m['base104']['sha256'];assert hashlib.sha256(cp.read_bytes()).hexdigest()==m['candidate113']['sha256'];bt=ast.parse(bs);ct=ast.parse(cs);assert cs.splitlines()[0]=='# codex-power v113';assert cs.startswith(bs.replace('# codex-power v104','# codex-power v113',1));assert len(ct.body)==len(bt.body)+2
for x,y in zip(bt.body,ct.body):assert ast.dump(x,include_attributes=False)==ast.dump(y,include_attributes=False)
imports=[ast.unparse(x) for x in ct.body if isinstance(x,(ast.Import,ast.ImportFrom))];assert imports==['import tilelang','from tilelang import language as T','from tilelang import DataType']
f=ct.body[-2];install=ct.body[-1];assert isinstance(f,ast.FunctionDef) and f.name=='_make_power_s4_global_softmax';assert ast.literal_eval(install.value.args[0])==(2,512,1,16,64,4,16,True);assert install.value.args[1].id==f.name
# Complete S4 factory is an exact specialization of own already validated S8 algorithm; no other arithmetic/layout edit.
expected=bs[bs.rfind('@tilelang.jit'):].replace('_make_power_s8_global_softmax','_make_power_s4_global_softmax').replace('selected_blocks == 8','selected_blocks == 4').replace('scores = T.alloc_local(32, accum_dtype)','scores = T.alloc_local(16, accum_dtype)').replace('probabilities = T.alloc_local(32, dtype)','probabilities = T.alloc_local(16, dtype)').replace('T.unroll(8)','T.unroll(4)').replace('T.unroll(32)','T.unroll(16)').replace('(4,1024,1,16,64,8,16,True)','(2,512,1,16,64,4,16,True)');et=ast.parse(expected);assert all(ast.dump(x,include_attributes=False)==ast.dump(y,include_attributes=False) for x,y in zip(et.body,ct.body[-2:]));assert len(et.body)==2
for n in ast.walk(f):
 if isinstance(n,ast.Call):
  name=ast.unparse(n.func);assert not any(a in name.lower() for a in ['async','external','call_extern','builtin'])
assert [ast.literal_eval(n.args[0]) for n in ast.walk(f) if isinstance(n,ast.Call) and ast.unparse(n.func)=='T.tvm_mfma']==['16x16x16f16','16x16x16f16']
result={'source_SHA':m['candidate113']['sha256'],'base_AST_nodes_preserved':len(bt.body),'extra_AST_nodes':2,'other13keys_includingC12_preserved':True,'exact3imports':imports,'MFMA_normal_only':True,'S4_only_specialization':True,'constant_offset_in_source_not_compiler_proof':True,'newSDK_attention_refs':0};(r/'source_validation.json').write_text(json.dumps(result,indent=2)+chr(10));(r/'source_validation.exit').write_text('0'+chr(10));print('V113_SOURCE_GATE',result)
