from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v118_worker1_c6_num16_v4_plane_lifetimes_sc-16g-2';r=b/'rep'/v;d=json.loads((r/'stage_result.json').read_text());res=json.loads((r/'SDK/resource_result.json').read_text());assert not d['complete'] and len(d['all_jobs'])==3 and d['metadata_pairs']==2 and d['all_jobs'][-1]['actual_exit']==1;assert res['MT']==90 and res['ST']==24 and res['staticmax']==5 and res['stack']==0 and res['dynamicshared']==8192;assert (r/'SDK/resource_actual.exit').read_text().strip()=='0' and (r/'SDK/resource_gate.exit').read_text().strip()=='1';assert not (r/'SDK/IR_actual.exit').exists() and not (r/'compiled_gate.exit').exists();assert all((r/k).read_text().strip()=='1' for k in ['launcher_actual.exit','supervisor_actual.exit','controller_actual.exit','stage.exit']);assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13;assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for folder,name in [('experiments','candidate.py'),('submission','submission.py')]:assert hashlib.sha256((b/folder/v/name).read_bytes()).hexdigest()=='290ac7d13d219d161d14833fcfa777df6ae809982708bb6a95f1a4172a3acf2e'
m=json.loads((r/'compile_source_manifest.json').read_text())
for x in list(m['sources'].values())+list(m['tools'].values())+[m['shared_identity_document'],m['parent_C6_device'],m['parent_C6_resource']]:assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
for name,sha in json.loads((r/'shared_inputs_identity.json').read_text())['files'].items():assert hashlib.sha256((root/name).read_bytes()).hexdigest()==sha
for x in json.loads((r/'metadata_pair.json').read_text())['records']:
 for k in ['device','host']:assert hashlib.sha256(Path(x[k+'_path']).read_bytes()).hexdigest()==x[k+'_SHA']
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'candidate_compiled_MT90_rejected_by_preregistered_MT_less_than90_no_native','candidate_SHA':'290ac7d13d219d161d14833fcfa777df6ae809982708bb6a95f1a4172a3acf2e','original_stage_result':d,'resource_actual':res,'runtime_final':json.loads((r/'runtime_final.json').read_text()),'references':json.loads((r/'reference_count_scope.json').read_text()),'CPP_readonly_observation':json.loads((r/'existing_CPP_lifetime_observation.json').read_text()),'strictMT_less90_not_relaxed':True,'IR_native_profile_notstarted':True,'other13_CB13prefix_preserved':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for x in ['experiments','hack','rep','submission']:(b/x/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for x in ['experiments','hack','rep','submission'] for f in (b/x/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==sha for f,sha in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((b/x/v).relative_to(root)) for x in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('V118_CLOSED',len(staged),len(idx),'MT90resourcegate1/noIR/native')
