from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v116_worker1_exact_parent_C6_C10_profile_resource_sc-16g-2';r=b/'rep'/v;d=json.loads((r/'stage_result.json').read_text());assert not d['complete'] and len(d['all_jobs'])==3 and d['all_jobs'][-1]['actual_exit']==1 and d['metadata_record_pairs']==4 and not d['resource_results'] and d['actual_counter_records']==0;assert all((r/k).read_text().strip()=='1' for k in ['launcher_actual.exit','supervisor_actual.exit','controller_actual.exit','stage.exit']);assert (r/'codegen_identity_recovery01_actual.exit').read_text().strip()==(r/'codegen_identity_recovery01.exit').read_text().strip()=='0';assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13;assert (r/'report_sc-16g-2.md').read_text().count('## ')==7;m=json.loads((r/'source_manifest.json').read_text())
for x in list(m['sources'].values())+list(m['tools'].values())+[m['shared_identity_document']]+list(m['existing_parent_devices'].values()):assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
for f,sha in json.loads((r/'shared_inputs_identity.json').read_text())['files'].items():assert hashlib.sha256((root/f).read_bytes()).hexdigest()==sha
for label in ['parent_v084','power_v113']:
 for x in json.loads((r/('metadata_'+label+'.json')).read_text())['records']:
  for k in ['device','host']:assert hashlib.sha256(Path(x[k+'_path']).read_bytes()).hexdigest()==x[k+'_sha256']
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'original_stage3_CPUparser_failed_independent_CPUidentity_recovery_complete','actual_original_stage_result':d,'CPUrecovery_originalwait':json.loads((r/'CPU_recovery01_wait.json').read_text()),'actual_identity_recovery':json.loads((r/'codegen_identity_recovery01_result.json').read_text()),'runtime_final':json.loads((r/'runtime_final.json').read_text()),'references':json.loads((r/'reference_count_scope.json').read_text()),'no_oldgate_rewrite_reexport_or_profile_execution':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for a in ['experiments','hack','rep','submission']:(b/a/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for a in ['experiments','hack','rep','submission'] for f in (b/a/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==s for f,s in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip();paths=[str((b/a/v).relative_to(root)) for a in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],check=True);print('V116_CLOSED',len(staged),len(idx),'4pairs8files/CPUrecovery0/resourceCLI0')
