from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v127_worker1_c6_v_operand_chunk_stream_sc-16g-2';r=b/'rep'/v;m=json.loads((r/'compile_source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());rt=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert not d['complete'] and d['failure']=='wholeCG exceeds new5GiB admission' and d['all_jobs']==[] and d['metadata_pairs']==0;assert rt['stage1child_spawned'] is False and rt['metadata_resource_IR_native_fullrefs']==0 and rt['all_self_jobs_terminal'];assert rt['OOM_initial_final']==[13,13] and all(x=='1' for x in rt['all_originalwaits'].values());assert not list(r.glob('stage_*/child.pid')) and not (r/'metadata_pair.json').exists() and not (r/'SDK').exists();assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for k,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document']),('parentCPP',m['parent_C6_device'])]:assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],k
for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
assert sha(b/'experiments'/v/'candidate.py')==sha(b/'submission'/v/'submission.py')=='cfeb8e5d18adb3c0d0c887633fc8dea1778ebfdfc100fdc9c9a77544c514515d';assert sha(b/'submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'compile_initial_admission_refused_no_backend_evidence','source_reference':m['sources']['candidate127'],'runtime':d,'runtime_final':rt,'refs':json.loads((r/'reference_count_scope.json').read_text()),'old5GiB_boundary1_notrelaxed':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
allfiles=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];files=[f for f in allfiles if '__pycache__' not in f.parts and f.suffix!='.pyc'];excluded=[str(f.relative_to(root)) for f in allfiles if f not in files];(r/'generated_cache_excluded.json').write_text(json.dumps({'files_notarchived_notdeleted':excluded,'nohistoryrewrite':True},indent=2)+chr(10));files.append(r/'generated_cache_excluded.json');idx={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();exact=list(idx)+[str((r/'archive_sha256.json').relative_to(root))];subprocess.run(['git','add','-f','--']+exact,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert sorted(staged)==sorted(exact) and not any('__pycache__' in f or f.endswith('.pyc') for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V127_CLOSURE_STAGED',len(staged),len(idx),'cacheexcluded',len(excluded),'0backend')
