from pathlib import Path
import json,hashlib,re
r=Path('/root/tilelang-metax/race_tests/nsa/rep/v127_worker1_c6_v_operand_chunk_stream_sc-16g-2');m=json.loads((r/'compile_source_manifest.json').read_text());ir=r/'SDK/candidate127.ll';x=next(x for x in json.loads((r/'metadata_pair.json').read_text())['records'] if x['variant']=='candidate127');dev=Path(x['device_path']);assert hashlib.sha256(dev.read_bytes()).hexdigest()==x['device_SHA'];res=json.loads((r/'SDK/resource_result.json').read_text());assert (r/'SDK/IR_actual.exit').read_text().strip()=='0';lines=ir.read_text().splitlines();entries=[i for i,l in enumerate(lines) if l.startswith('define ') and '@native_sparse_attention_kernel(' in l];assert len(entries)==1;start=entries[0];end=next(i for i in range(start+1,len(lines)) if lines[i].strip()=='}');body=lines[start:end+1]
MMA=[{'line':i,'text':l} for i,l in enumerate(body,start+1) if 'call' in l and '@llvm.mxc.mma.f32.16x16x16f16' in l];alloc=[{'line':i,'text':l} for i,l in enumerate(body,start+1) if re.search(r'^\s*%[^=]+\s*=\s*alloca\b',l)];private=[{'line':i,'text':l} for i,l in enumerate(body,start+1) if 'addrspace(5)' in l];events=[{'line':i,'text':l} for i,l in enumerate(body,start+1) if any(t in l for t in ['addrspace(3)','mma.f32','barrier','phi ','br i1','fptrunc','fdiv'])];cpp=[{'line':i,'text':l} for i,l in enumerate(dev.read_text().splitlines(),1) if any(t in l for t in ['__syncthreads','__syncwarp','partial_maximum','partial_denominator','partial_numerator','probabilities','numerator','warp_id','kv_offset'])]
ok=bool(MMA) and not alloc and not private and res['stack']==0 and res['dynamicshared']==next(y['actual_launchargs'][-1] for y in json.loads((r/'device_shape_static_result.json').read_text())['checks'] if y['variant']=='candidate127')
out={'resource':res,'IR_SHA':hashlib.sha256(ir.read_bytes()).hexdigest(),'actual_static_MMA_count':len(MMA),'MMA_call_lines':MMA,'fullvalid_dynamic_model':'C6singlewarp32MMA source model; recordactualIRcall/loops, notruntimecount','alloca_opcode_lines':alloc,'AS5_lines':private,'mechanical_gate':ok,'actual_math_sync_lifetime_review':'PENDING leader review of actual CPP/IR currentC6 Num32/parentP8den/samekey-plane-chunkV4loadMMAdefuse/allproducer-sync-output widths; nohoist/physreg assumption; no automaticnative','no_physical_liveness_occupancy_or_latency_claim':True,'fullrefs':0}
for name,data in [('compiled_observation_result.json',out),('compiled_IR_events.json',events),('compiled_CPP_events.json',cpp)]:
 (r/name).write_text(json.dumps(data,indent=2)+chr(10))
(r/'compiled_observation.exit').write_text(str(0 if ok else 1)+chr(10));print('COMPILED_MECHANICAL_OBSERVATION',ok,len(MMA),res,flush=True);raise SystemExit(0 if ok else 1)
