from pathlib import Path
import json,hashlib,subprocess
p=Path('/root/tilelang-metax/race_tests/nsa');r=p/'rep/v111_worker1_shared_identity_preflight_codegen_sc-16g-2';m=json.loads((r/'source_manifest.json').read_text());cases=json.loads((p/'official_case.json').read_text());records={};checks=[]
for label in ['parent_v084','power_v104']:
 data=json.loads((r/('metadata_'+label+'.json')).read_text());assert data['NSA_attention_calls']==data['full_reference_checks']==0 and len(data['records'])==14
 for i,x in enumerate(data['records'],1):
  assert x['case']==i and x['hook_count_in_case']==1 and not x['actual_NSA_launch_after_hook'];assert x['source_sha256']==m['sources'][label]['sha256'];c=cases[i-1];expected=[[c['B'],c['SEQ_LEN'],c['HQ'],c['D']],[c['B'],c['SEQ_LEN'],c['H'],c['D']],[c['B'],c['SEQ_LEN'],c['H'],c['D']],[c['B'],c['SEQ_LEN'],c['H'],c['S']],[c['B'],c['SEQ_LEN'],c['HQ'],c['D']]];assert [a['shape'] for a in x['argument_metadata']]==expected;assert [a['dtype'] for a in x['argument_metadata']]==['torch.float16']*3+['torch.int32','torch.float16']
  for name in ['device','host']:assert hashlib.sha256(Path(x[name+'_path']).read_bytes()).hexdigest()==x[name+'_sha256']
  records[(label,i)]=x
 source=m['sources'][label]['path'];cmd=[m['tools']['python']['path'],'-S',m['tools']['validator']['path'],source]+[part for x in data['records'] for part in ['--generated-code',x['device_path']]];result=subprocess.run(cmd,capture_output=True,text=True);(r/(label+'_static_command.json')).write_text(json.dumps({'command':cmd},indent=2)+chr(10));(r/(label+'_static.log')).write_text(result.stdout+result.stderr);(r/(label+'_static.exit')).write_text(str(result.returncode)+chr(10));assert result.returncode==0
for ci in range(1,15):
 a=records[('parent_v084',ci)];b=records[('power_v104',ci)];same=Path(a['device_path']).read_bytes()==Path(b['device_path']).read_bytes();checks.append({'case':ci,'parent_device_sha256':a['device_sha256'],'candidate_device_sha256':b['device_sha256'],'actual_device_byte_identical':same,'expected_same':ci!=12,'not_performance_waiver':True})
old=p/'rep/v104_worker1_s8_global_softmax_sc-16g-2/codegen_precompile/power_v104/case12_stage1.device.cpp';c12=records[('power_v104',12)];oldmatch=Path(c12['device_path']).read_bytes()==old.read_bytes();(r/'codegen_identity_result.json').write_text(json.dumps({'checks':checks,'C12_byte_equal_validated_v104_CPP':oldmatch,'validated104CPP_SHA256':hashlib.sha256(old.read_bytes()).hexdigest(),'metadata_pairs':28,'generated_files':56,'NSA_attention_calls':0,'reference_checks':0,'all_original_latency_positive_retained':True},indent=2)+chr(10));assert all(x['actual_device_byte_identical'] for x in checks if x['case']!=12) and oldmatch;(r/'codegen_identity.exit').write_text('0'+chr(10));print('ACTUAL_CODEGEN_IDENTITY0',28,56)
