from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');p=root/'race_tests/nsa';v='v111_worker1_shared_identity_preflight_codegen_sc-16g-2';r=p/'rep'/v;m=json.loads((r/'source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());assert d['complete'] and len(d['all_jobs'])==7 and d['metadata_record_pairs']==28 and len(d['resource_results'])==4;assert (r/'stage.exit').read_text().strip()==(r/'controller_actual.exit').read_text().strip()=='0';assert d['cgroup_initial']['oom_kill']==d['cgroup_final']['oom_kill']==13 and all(x['actual_exit']==0 and not x['stop_reason'] for x in d['all_jobs']);assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for name in ['master.pid','supervisor.pid']:assert subprocess.run(['kill','-0',(r/name).read_text().strip()],capture_output=True).returncode!=0
for x in list(m['sources'].values())+list(m['tools'].values())+[m['shared_identity_document']]:assert Path(x['path']).is_file() and hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256']
for name,sha in json.loads((r/'shared_inputs_identity.json').read_text())['files'].items():assert hashlib.sha256((root/name).read_bytes()).hexdigest()==sha
for label in ['parent_v084','power_v104']:
 a=json.loads((r/('metadata_'+label+'.json')).read_text());assert len(a['records'])==14 and a['NSA_attention_calls']==a['full_reference_checks']==0
 for x in a['records']:
  assert x['hook_count_in_case']==1
  for k in ['device','host']:assert hashlib.sha256(Path(x[k+'_path']).read_bytes()).hexdigest()==x[k+'_sha256']
a=json.loads((r/'codegen_identity_result.json').read_text());assert a['C12_byte_equal_validated_v104_CPP'] and all(x['actual_device_byte_identical'] for x in a['checks'] if x['case']!=12);assert (r/'codegen_identity.exit').read_text().strip()=='0';assert not (p/'rep/v110_worker1_parent_resources_and_codegen_identity_sc-16g-2/stage.exit').exists()
(r/'manifest.json').write_text(json.dumps({'version':v,'status':'metadata_resource_complete_source13_identical_C11_physical_filled','closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stage_result':d,'codegen_identity':a,'source_manifest':m,'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'runtime_final':json.loads((r/'runtime_final.json').read_text()),'old_v110_startupfailure_not_rewritten':True,'no_newkernel_or_native_or_IR_or_profile':True,'latency_positive_not_waived':True,'OJ':None,'main_promotion':False},indent=2)+chr(10))
for a in ['experiments','hack','rep','submission']:(p/a/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10)+'*.patch -diff'+chr(10))
files=[f for a in ['experiments','hack','rep','submission'] for f in (p/a/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(hashlib.sha256((root/f).read_bytes()).hexdigest()==sha for f,sha in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((p/a/v).relative_to(root)) for a in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(x+'/') for x in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V111_CLOSED',len(staged),len(idx),'28pairs4SDK0NSA/ref')
