from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/root/tilelang-metax');b=root/'race_tests/nsa';v='v123_worker1_c12_parallel_shared_counter_diagnostic_sc-16g-2';r=b/'rep'/v;m=json.loads((r/'source_manifest.json').read_text());d=json.loads((r/'stage_result.json').read_text());rt=json.loads((r/'runtime_final.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
assert d['complete'] and len(d['all_jobs'])==2 and all(x['actual_exit']==0 for x in d['all_jobs']);assert d['actual_counter_records']==d['valid_scope_records']==4 and rt['OOM_values']==[13] and rt['all_self_jobs_terminal'];assert all(x=='0' for x in rt['outer_originalwaits'].values()) and all(x['actual_CLI_waitcode']==0 for x in rt['SDK_originalwaits']);assert (r/'report_sc-16g-2.md').read_text().count('## ')==7
for k,x in list(m['sources'].items())+list(m['tools'].items())+[('shared_doc',m['shared_identity_document'])]+list(m['reused_artifacts'].items()):assert Path(x['path']).is_file() and sha(x['path'])==x['sha256'],k
for f,s0 in json.loads(Path(m['shared_identity_document']['path']).read_text())['files'].items():assert sha(root/f)==s0
assert (b/'rep/v121_worker1_c12_two_warp_selected_partition_sc-16g-2/stage.exit').read_text().strip()=='1';assert sha(b/'submission.py')=='42911561dd0c60770cf9815607ca08794c98f1dd9d4ee2abfe9ef6bd70bca6dd'
(r/'manifest.json').write_text(json.dumps({'version':v,'closedUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'finite_raw_profile_completed_shared_regression_observed_no_unique_cause','runtime':d,'runtime_final':rt,'counters':json.loads((r/'counter_comparison.json').read_text()),'reference_counts':json.loads((r/'reference_count_scope.json').read_text()),'old122latency_and121gate1_preserved':True,'main_promotion':False,'OJ':None},indent=2)+chr(10))
for folder in ['experiments','hack','rep','submission']:(b/folder/v/'.gitattributes').write_text('* -text -eol -diff'+chr(10))
files=[f for folder in ['experiments','hack','rep','submission'] for f in (b/folder/v).rglob('*') if f.is_file() and f.name!='archive_sha256.json'];idx={str(f.relative_to(root)):sha(f) for f in sorted(files)};(r/'archive_sha256.json').write_text(json.dumps(idx,indent=2)+chr(10));assert all(sha(root/f)==s0 for f,s0 in idx.items());assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip();paths=[str((b/folder/v).relative_to(root)) for folder in ['experiments','hack','rep','submission']];subprocess.run(['git','add','-f','--']+paths,cwd=root,check=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).splitlines();assert len(staged)==len(files)+1 and all(any(f.startswith(z+'/') for z in paths) for f in staged);subprocess.run(['git','-c','core.whitespace=-blank-at-eof','diff','--cached','--check'],cwd=root,check=True);print('V123_CLOSURE_STAGED',len(staged),len(idx),'raw4/0outside')
